language: php

sudo: false

php: [5.3, 5.4, 5.5, 5.6, hhvm]

matrix:
  fast_finish: true

install: composer install

script: phpunit --coverage-clover build/logs/clover.xml

after_script:
    - if [ "$TRAVIS_PHP_VERSION" != "hhvm" ]; then php vendor/bin/coveralls -v; fi;
